//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\beaulacj\Downloads\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /namespace:"Crm.Xrm.Plugins.BlitzCapstone" /out:"C:\Users\beaulacj\Downloads\XrmToolBox\Plugins\CrmSvcUtil Ref\CroweBlitz\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /connectionstring:"Url=https://crm2016dev.crowehorwath.com/BlitzCapStone;Domain=crowedevcrm;UserName=beaulacjn;Password=*********" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace CH.Xrm.Plugins.Models.Entities
{

    /// <summary>
    /// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CH.Xrm.Plugins.Models.Entitiesch_menuitem"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CH.Xrm.Plugins.Models.Entities.ch_menuitem> ch_menuitemSet
		{
			get
			{
				return this.CreateQuery<CH.Xrm.Plugins.Models.Entities.ch_menuitem>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CH.Xrm.Plugins.Models.Entitiesch_order"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CH.Xrm.Plugins.Models.Entities.ch_order> ch_orderSet
		{
			get
			{
				return this.CreateQuery<CH.Xrm.Plugins.Models.Entities.ch_order>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CH.Xrm.Plugins.Models.Entitiesch_orderitem"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CH.Xrm.Plugins.Models.Entities.ch_orderitem> ch_orderitemSet
		{
			get
			{
				return this.CreateQuery<CH.Xrm.Plugins.Models.Entities.ch_orderitem>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CH.Xrm.Plugins.Models.Entitiesch_pizzatopping"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CH.Xrm.Plugins.Models.Entities.ch_pizzatopping> ch_pizzatoppingSet
		{
			get
			{
				return this.CreateQuery<CH.Xrm.Plugins.Models.Entities.ch_pizzatopping>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="CH.Xrm.Plugins.Models.Entitiesch_textmessage"/> entities.
		/// </summary>
		public System.Linq.IQueryable<CH.Xrm.Plugins.Models.Entities.ch_textmessage> ch_textmessageSet
		{
			get
			{
				return this.CreateQuery<CH.Xrm.Plugins.Models.Entities.ch_textmessage>();
			}
		}
	}
	
	internal sealed class EntityOptionSetEnum
	{
		
		public static System.Nullable<int> GetEnum(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)
		{
			if (entity.Attributes.ContainsKey(attributeLogicalName))
			{
				Microsoft.Xrm.Sdk.OptionSetValue value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>(attributeLogicalName);
				if (value != null)
				{
					return value.Value;
				}
			}
			return null;
		}
	}
}