//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH.Xrm.Plugins.Models.Entities
{

    [System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum ch_order_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cancelled = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Delivered = 881830002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 881830000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutforDelivery = 881830001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Submitted = 1,
	}
}