//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH.Xrm.Plugins.Models.Entities
{

    [System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum ch_PizzaToppings
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Anchovies = 881830006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Bacon = 881830004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BlackOlives = 881830005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GreenPeppers = 881830007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Mushrooms = 881830001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pepperoni = 881830000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pineapple = 881830003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sausage = 881830002,
	}
}