//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH.Xrm.Plugins.Models.Entities
{

    [System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.1.0.7711")]
	public enum ch_textmessage_InstanceTypeCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotRecurring = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringException = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringFutureException = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringInstance = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringMaster = 1,
	}
}